### ISSUE TITLE
jax.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected

### ISSUE THREAD

**Issue by carlosgmartin** [MIT-Lu-Lab/MPAX#1]
Thanks for creating this repo!

I'm testing it on a small problem:

<details>

<summary>Code</summary>

```python3
import cvxpy as cp
import jax
import mpax
import numpy as np
from jax import numpy as jnp, random
from matplotlib import pyplot as plt


@jax.jit
def solve_cvxpy(A):
    """Maximize sum(x) subject to A @ x <= 1."""

    A_param = cp.Parameter(A.shape)
    x = cp.Variable(A.shape[1])

    objective = cp.Maximize(x.sum())
    constraints = [A_param @ x <= 1]
    problem = cp.Problem(objective, constraints)  # type: ignore

    def f(A):
        A_param.value = np.array(A)
        problem.solve(solver="CLARABEL")
        return jnp.array(x.value)

    return jax.pure_callback(
        f, jnp.empty(x.shape), A, vmap_method="sequential"
    )


def solve_mpax(A):
    # A = BCOO.fromdense(A, nse=A.size)
    m, d = A.shape
    lp = mpax.create_lp(
        c=-jnp.ones(d),
        A=A,
        l=jnp.full(m, -jnp.inf),
        u=jnp.ones(m),
        var_lb=jnp.full(d, -jnp.inf),
        var_ub=jnp.full(d, +jnp.inf),
    )
    solver = mpax.r2HPDHG(eps_abs=1e-4, eps_rel=1e-4, verbose=False)
    result = solver.optimize(lp)
    return result.primal_solution


def main():
    key = random.key(0)
    A = jnp.abs(random.normal(key, [10**4, 100, 2]))

    x = jax.vmap(jax.jit(solve_cvxpy))(A)
    plt.plot(*x.T, ".", ms=1, label="cvxpy")

    plt.legend()
    plt.pause(1)

    x = jax.vmap(jax.jit(solve_mpax))(A)
    plt.plot(*x.T, ".", ms=1, label="mpax")

    plt.legend()
    plt.show()


if __name__ == "__main__":
    main()
```

</details>

Here is the output:

<details>

<summary>Output</summary>

```
$ py lp_example.py
Traceback (most recent call last):
  File "/Users/carlos/Documents/cmu/research/code/monorepo/lp_example.py", line 63, in <module>
    main()
  File "/Users/carlos/Documents/cmu/research/code/monorepo/lp_example.py", line 55, in main
    x = jax.vmap(jax.jit(solve_mpax))(A)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/traceback_util.py", line 180, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/api.py", line 992, in vmap_f
    out_flat = batching.batch(
               ^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/linear_util.py", line 193, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/traceback_util.py", line 180, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/pjit.py", line 338, in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr, attrs_tracked = _python_pjit_helper(
                                                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/pjit.py", line 178, in _python_pjit_helper
    p, args_flat = _infer_params(fun, jit_info, args, kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/pjit.py", line 744, in _infer_params
    p, args_flat = _infer_params_impl(
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/pjit.py", line 641, in _infer_params_impl
    jaxpr, consts, out_avals, attrs_tracked = _create_pjit_jaxpr(
                                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/linear_util.py", line 352, in memoized_fun
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/pjit.py", line 1288, in _create_pjit_jaxpr
    jaxpr, global_out_avals, consts, attrs_tracked = pe.trace_to_jaxpr_dynamic(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/profiler.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/interpreters/partial_eval.py", line 2278, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts, attrs_tracked = trace_to_subjaxpr_dynamic(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/interpreters/partial_eval.py", line 2301, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/linear_util.py", line 193, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/Documents/cmu/research/code/monorepo/lp_example.py", line 32, in solve_mpax
    lp = mpax.create_lp(
         ^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/mpax/mp_io.py", line 213, in create_lp
    A = BCOO.fromdense(A)
        ^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/experimental/sparse/bcoo.py", line 2529, in fromdense
    return bcoo_fromdense(
           ^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/experimental/sparse/bcoo.py", line 266, in bcoo_fromdense
    nse_int = core.concrete_or_error(operator.index, nse_arr, _TRACED_NSE_ERROR)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/core.py", line 1571, in concrete_or_error
    raise ConcretizationTypeError(val, context)
jax.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: traced array with shape int32[]

The error arose for the nse argument of bcoo_fromdense. In order for
BCOO.fromdense() to be used in traced/compiled code, you must pass a concrete
value to the nse (number of stored elements) argument.

The error occurred while tracing the function solve_mpax at /Users/carlos/Documents/cmu/research/code/monorepo/lp_example.py:30 for jit. This concrete value was not available in Python because it depends on the value of the argument A.

See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
```

</details>

As you can see, when the `solve` function is traced by JAX, it raises a `ConcretizationTypeError` because of the call to `BCOO.fromdense` in [this line of code](https://github.com/MIT-Lu-Lab/MPAX/blob/59b0ea78705cf3521a40835dff3e4f6a7e8b6d2d/mpax/mp_io.py#L213).

The second issue is that, if I uncomment the first commented line inside `solve_mpax` to convert `A` to a `BCOO` myself, I get another error:

<details>

<summary>Output</summary>

```
$ py lp_example.py
Traceback (most recent call last):
  File "/Users/carlos/Documents/cmu/research/code/monorepo/lp_example.py", line 67, in <module>
    main()
  File "/Users/carlos/Documents/cmu/research/code/monorepo/lp_example.py", line 59, in main
    x = jax.vmap(jax.jit(solve_mpax))(A)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/traceback_util.py", line 180, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/api.py", line 992, in vmap_f
    out_flat = batching.batch(
               ^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/linear_util.py", line 193, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/traceback_util.py", line 180, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/pjit.py", line 338, in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr, attrs_tracked = _python_pjit_helper(
                                                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/pjit.py", line 178, in _python_pjit_helper
    p, args_flat = _infer_params(fun, jit_info, args, kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/pjit.py", line 744, in _infer_params
    p, args_flat = _infer_params_impl(
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/pjit.py", line 641, in _infer_params_impl
    jaxpr, consts, out_avals, attrs_tracked = _create_pjit_jaxpr(
                                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/linear_util.py", line 352, in memoized_fun
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/pjit.py", line 1288, in _create_pjit_jaxpr
    jaxpr, global_out_avals, consts, attrs_tracked = pe.trace_to_jaxpr_dynamic(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/profiler.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/interpreters/partial_eval.py", line 2278, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts, attrs_tracked = trace_to_subjaxpr_dynamic(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/interpreters/partial_eval.py", line 2301, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/linear_util.py", line 193, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/Documents/cmu/research/code/monorepo/lp_example.py", line 36, in solve_mpax
    lp = mpax.create_lp(
         ^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/mpax/mp_io.py", line 237, in create_lp
    return transform_to_standard_form(problem)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/mpax/mp_io.py", line 24, in transform_to_standard_form
    two_sided_rows_to_slacks(qp)
  File "/Users/carlos/venv/lib/python3.12/site-packages/mpax/mp_io.py", line 134, in two_sided_rows_to_slacks
    two_sided_rows = jnp.where(
                     ^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/numpy/lax_numpy.py", line 2924, in where
    return nonzero(condition, size=size, fill_value=fill_value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/numpy/lax_numpy.py", line 3840, in nonzero
    calculated_size: int = core.concrete_dim_or_error(calculated_size_,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/core.py", line 1580, in concrete_dim_or_error
    return concrete_or_error(operator.index, val, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlos/venv/lib/python3.12/site-packages/jax/_src/core.py", line 1571, in concrete_or_error
    raise ConcretizationTypeError(val, context)
jax.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: traced array with shape int32[]
The size argument of jnp.nonzero must be statically specified to use jnp.nonzero within JAX transformations.
The error occurred while tracing the function solve_mpax at /Users/carlos/Documents/cmu/research/code/monorepo/lp_example.py:31 for jit. This value became a tracer due to JAX operations on these lines:

  operation a:f32[] = convert_element_type[new_dtype=float32 weak_type=True] b
    from line /Users/carlos/Documents/cmu/research/code/monorepo/lp_example.py:39:10 (solve_mpax)

  operation a:f32[] = convert_element_type[new_dtype=float32 weak_type=False] b
    from line /Users/carlos/Documents/cmu/research/code/monorepo/lp_example.py:40:10 (solve_mpax)

See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
```

</details>

This time, the error is raised by the call to `jnp.where` in [this line of code](https://github.com/MIT-Lu-Lab/MPAX/blob/59b0ea78705cf3521a40835dff3e4f6a7e8b6d2d/mpax/mp_io.py#L134).

**Comment by ZedongPeng** [comment]
Hi @carlosgmartin,  

Thank you for your input!  

Currently, the `create_lp` function does not support `jax.jit`. However, the `solver.optimize` function is compatible with `jax.jit`. For now, you can only apply `jax.jit` to the `optimize` function.  

I’ll work on updating the `create_lp` function to make it compatible with `jax.jit` soon.

**Comment by ZedongPeng** [comment]
Hi @carlosgmartin. 
The previous `create_lp(c, A, l, u, var_lb, var_ub)` function supported two-sided constraints, which made the number of constraints in the standard form uncertain. To address this, we revised it to `create_lp(c, A, b, G, h, l, u)`, and it is now fully jittable.

**Comment by carlosgmartin** [comment]
@ZedongPeng Thanks! It seems to work now:

<details>

<summary>Code</summary>

```python3
import cvxpy as cp
import jax
import mpax
import numpy as np
from jax import numpy as jnp, random
from matplotlib import pyplot as plt


@jax.jit
def solve_cvxpy(A):
    """Maximize sum(x) subject to A @ x <= 1."""

    A_param = cp.Parameter(A.shape)
    x = cp.Variable(A.shape[1])

    objective = cp.Maximize(x.sum())
    constraints = [A_param @ x <= 1]
    problem = cp.Problem(objective, constraints)  # type: ignore

    def f(A):
        A_param.value = np.array(A)
        problem.solve(solver="CLARABEL")
        return jnp.array(x.value)

    return jax.pure_callback(
        f, jnp.empty(x.shape), A, vmap_method="sequential"
    )


def solve_mpax(A):
    m, d = A.shape
    lp = mpax.create_lp(
        c=-jnp.ones(d),
        A=jnp.zeros([0, d]),
        b=jnp.zeros(0),
        G=-A,
        h=-jnp.ones(m),
        l=jnp.full(d, -jnp.inf),
        u=jnp.full(d, +jnp.inf),
    )
    solver = mpax.r2HPDHG(eps_abs=1e-4, eps_rel=1e-4, verbose=False)
    result = solver.optimize(lp)
    return result.primal_solution


def main():
    batch_size = 10**2
    n_constraints = 100

    key = random.key(0)
    A = jnp.abs(random.normal(key, [batch_size, n_constraints, 2]))

    print("cvxpy...", end="", flush=True)
    x = jax.vmap(jax.jit(solve_cvxpy))(A)
    plt.plot(*x.T, ".", ms=10, label="cvxpy", alpha=0.5)
    print(" done")

    print("mpax...", end="", flush=True)
    x = jax.vmap(jax.jit(solve_mpax))(A)
    plt.plot(*x.T, ".", ms=10, label="mpax", alpha=0.5)
    print(" done")

    plt.legend()
    plt.show()


if __name__ == "__main__":
    main()
```

</details>

![image](https://github.com/user-attachments/assets/1781ba29-9443-424d-9df6-2b6041d9434c)

Would you also consider relaxing the dependency specification in [`pyproject.toml`](https://github.com/MIT-Lu-Lab/MPAX/blob/main/pyproject.toml) (e.g. changing `^` or `==` to `>=`)? Currently, its restrictiveness causes some conflicts for me. I can override this manually, but that would be more convenient.

**Comment by ZedongPeng** [comment]
Hi @carlosgmartin . Thank you for your suggestion. I will work on the dependencies.

**Comment by ZedongPeng** [comment]
The `numpy` version has been changed to `">1.24.4, <2.3"` in `v0.1.1`. Feel free to update MPAX and try it out.

**Comment by carlosgmartin** [comment]
@ZedongPeng Thanks! Does it need to be pinned to `jax==0.4.35`? The latest release is [0.4.37](https://github.com/jax-ml/jax/releases/tag/jax-v0.4.37).

**Comment by ZedongPeng** [comment]
Thank you for the suggestion. I remember that some JAX versions produced unexpected results. I'll test the latest version, and if it works, I'll update it to `jax>=0.4.35`.
